version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/usr/src/notes
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
