# Generated by Django 3.1.4 on 2020-12-08 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='identifier')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
            ],
        ),
    ]
