# Generated by Django 3.1.4 on 2020-12-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='text'),
        ),
    ]
